services:
  client:
    build:
      context: ./
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/pomodoro
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

networks:
  pomodoro:
    name: pomodoro
    driver: bridge

volumes:
  mongodb_data:
