services:
  db:
    image: mongo:latest
    container_name: mongodb_dev
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_dev:/data/db
    restart: unless-stopped
    networks:
      - pomodoro_dev

networks:
  pomodoro_dev:
    name: pomodoro_dev
    driver: bridge

volumes:
  mongodb_data_dev: