services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pomodoro_dev

networks:
  pomodoro_dev:
    name: pomodoro_dev
    driver: bridge

volumes:
  pgdata:
