import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.scss';
import { Header } from '@/components/Header';
import clsx from 'clsx';

const roboto = Roboto({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '500', '400', '700', '100'],
});

export const metadata: Metadata = {
  title: 'Pomodoro',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          roboto.className,
          'text-2xl text-[#333] dark:bg-[#34495E] dark:text-[#BDC3C7]',
        )}
      >
        <header className='w-full px-0 py-4 text-[#DC3E22] shadow-md dark:bg-[#2C3E50] dark:text-[#ECF0F1]'>
          <Header />
        </header>
        <main className='max-w-[1440px] mx-auto'>{children}</main>
        <div id='modal' />
      </body>
    </html>
  );
}
